name: youtube_shorts
description: A vertical youtube shorts player. Show youtube shorts videos by a list of urls or the target channel name.
version: 0.4.5
homepage: https://pub.dev/packages/youtube_shorts
repository: https://github.com/igormidev/youtube_shorts
issue_tracker: https://github.com/igormidev/youtube_shorts/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.0.2
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  dart_debouncer: ^1.0.0
  synchronized: ^3.1.0
  easy_isolate_mixin: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

screenshots:
  - description: A visual demonstration of the cursor.
    path: art/screen_shot_1.PNG
  
topics:
  - layout
  - ui
  - youtube
  - webscrapping
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
